[build]
  # Thư mục chứa các file public như index.html
  publish = "public"
  # Thư mục chứa các serverless functions
  functions = "functions"

[functions]
  # Đảm bảo các dependencies của function được cài đặt
  node_bundler = "esbuild"